#
# This travis-ci build matrix config is a modified copy of the one from Astropy
#


# We can't use `language: python` here because it's not supported on Mac.
# But that's OK ... the language here is irrelevant because we use conda
# to install our own Python.
language: c

os:
    - linux

# This is a signal to travis-ci to use the new build infrastructure
sudo: false

addons:
  apt:
    packages: &default_apt
      - graphviz
      - texlive-latex-extra
      - dvipng
      - gfortran

env:
    global:
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=1.1
        - LIBGFORTRAN_VERSION=1.0
        - CONDA_DEPENDENCIES='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes sherpa libgfortran=$LIBGFORTRAN_VERSION'
        - CONDA_DEPENDENCIES_OSX='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes sherpa'
        - CONDA_DEPENDENCIES_WO_SHERPA='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes'
        - CONDA_DOCS_DEPENDENCIES='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes pygments aplpy sherpa libgfortran=$LIBGFORTRAN_VERSION'
        - CONDA_DOCS_DEPENDENCIES_WO_SHERPA='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes pygments aplpy'
        - CONDA_DEPENDENCIES_NOTEBOOKS='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes aplpy sherpa libgfortran=$LIBGFORTRAN_VERSION runipy'
        - CONDA_DEPENDENCIES_NOTEBOOKS_WO_SHERPA='Cython click scipy h5py matplotlib pyyaml scikit-image scikit-learn pandas naima photutils wcsaxes aplpy libgfortran=$LIBGFORTRAN_VERSION runipy'
        - PIP_DEPENDENCIES='regions uncertainties reproject'
        - CONDA_CHANNELS='astropy sherpa'
        - FETCH_GAMMAPY_EXTRA=true
        - MAIN_CMD='python setup.py'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try MacOS X
        - os: osx
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_OSX

        - os: osx
          env: PYTHON_VERSION=3.5 SETUP_CMD='test'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA

        # Temporarily disabled because of this issue:
        # https://travis-ci.org/gammapy/gammapy/jobs/115820975
        # https://github.com/gammapy/gammapy/pull/483
        # Test the dev version of Sherpa, this may take a longer time
        #- os: linux
        #  env: PYTHON_VERSION=2.7 SETUP_CMD='test -V'
        #       CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA DEBUG=True
        #       PIP_DEPENDENCIES='uncertainties reproject git+http://github.com/sherpa/sherpa.git#egg=sherpa'

        # Run tests
        # Coverage is measured on Python 2 (where Sherpa is available)
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test -V --coverage'

        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA

        # Build docs
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES=$CONDA_DOCS_DEPENDENCIES_WO_SHERPA

        # Run tests without GAMMAPY_EXTRA available
        - os: linux
          env: FETCH_GAMMAPY_EXTRA=false PYTHON_VERSION=3.5 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA
        # Test with Astropy dev and LTS versions
#        - os: linux
#          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=lts SETUP_CMD='test -V'
#        - os: linux
#          env: PYTHON_VERSION=3.5 ASTROPY_VERSION=lts SETUP_CMD='test -V'
#               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=dev SETUP_CMD='test -V'
        - os: linux
          env: PYTHON_VERSION=3.5 ASTROPY_VERSION=dev SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA

        # Test with with optional dependencies disabled
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES='Cython click'
               PIP_DEPENDENCIES='regions'
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='test -V'
               CONDA_DEPENDENCIES='Cython click'
               PIP_DEPENDENCIES='regions'

        # Test with other numpy versions. Not all of the packages are
        # available with these on conda, thus moving some of them to pip
        # install. Latest astropy stable (1.1) is also not available for
        # older numpies, but using lts version should be good enough for
        # these tests (so we can avoid building it from source).
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=dev SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=prerelease SETUP_CMD='test -V'

#        - os: linux
#          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.9 SETUP_CMD='test -V'
#               ASTROPY_VERSION=lts
#        - os: linux
#          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.8 SETUP_CMD='test -V'
#               ASTROPY_VERSION=lts
#               CONDA_CHANNELS='astropy-ci-extras astropy'
#               CONDA_DEPENDENCIES='Cython click matplotlib'
#               PIP_DEPENDENCIES=''

        # Test IPython notebooks
        - os: linux
          env: PYTHON_VERSION=3.4 MAIN_CMD='make' SETUP_CMD='test-notebooks'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_NOTEBOOKS_WO_SHERPA

        - os: linux
          env: PYTHON_VERSION=2.7 MAIN_CMD='make' SETUP_CMD='test-notebooks'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_NOTEBOOKS
    # You can move builds that temporarily fail because of some non-Gammapy
    # issue here
    # Please add a link to a GH issue that tracks the upstream issue.
    allow_failures:
        # see https://github.com/gammapy/gammapy/issues/439
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=dev SETUP_CMD='test -V'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES_WO_SHERPA
        # this halts at the moment and thus allowing it to fail, to be able to go
        # ahead with the release
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=prerelease SETUP_CMD='test -V'

install:
    - git clone -b rm-fixed-cov git://github.com/pllim/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    - if $FETCH_GAMMAPY_EXTRA; then
          git clone https://github.com/gammapy/gammapy-extra.git $HOME/gammapy-extra;
          export GAMMAPY_EXTRA=${HOME}/gammapy-extra;
      fi

    # This is needed to make matplotlib plot testing work
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          export QT_API=pyqt;
      fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test -V --coverage' ]]; then
          coveralls --rcfile='gammapy/tests/coveragerc';
      fi
